name: Auto Pull Request By Release

on:
  repository_dispatch:
    types: [ webhook ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.11'

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl
          tag: v0.0.46

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v2.0.0
        with:
          pulumi-version: 3.210.0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 21.X

      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.408

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.13

      - name: generate-code
        id: generate-code
        run: |
          version=`curl https://api.github.com/repos/tencentcloudstack/terraform-provider-tencentcloud/releases/latest --header 'Accept: application/vnd.github+json' --header 'Authorization: Bearer ${{secrets.GITHUB_TOKEN}}' | jq .name | tr -d '"' | tr -d 'v'`
          echo "version=$version" >> "$GITHUB_OUTPUT"
          
          git clone https://hellertang:${{secrets.GITHUB_TOKEN}}@github.com/tencentcloudstack/pulumi-tencentcloud.git
          cd pulumi-tencentcloud
          git config --global user.email "hellertang@tencent.com"
          git config --global user.name "hellertang"
          git checkout -b "feat/sync_provider_v${version}"

          cd provider && go get -v github.com/tencentcloudstack/terraform-provider-tencentcloud@v${version} && go mod tidy && cd -
          make tfgen
          make provider
          make build_sdks
          cd sdk && go mod tidy && cd -
          
          git add .
          git commit -sm "sync provider"
          git push origin feat/sync_provider_v${version}

      - name: create pull request
        run: |
          cd pulumi-tencentcloud
          gh pr create -B main -H feat/sync_provider_v${{ steps.generate-code.outputs.version }} --title "sync terraform provider v${{ steps.generate-code.outputs.version }}" --body "sync terraform provider version to v${{ steps.update-code.outputs.version }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
